apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: voidchan-ns
spec:
  tls:
  - hosts:
    - cdn.voidchan.gg
    secretName: cloudflare
  rules:
  - host: cdn.voidchan.gg
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: voidchan-api-service
            port:
              number: 80
