apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: voidchan-ns
spec:
  ingressClassName: istio
  rules:
  - host: cdn.voidchan.gg
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: voidchan-api-service
          servicePort: 3000
  tls:
  - hosts:
    - cdn.voidchan.gg
    secretName: cloudflare
---
apiVersion: v1
kind: Service
metadata:
  name: voidchan-api-service
  namespace: voidchan-ns
  labels:
    app: voidchan
spec:
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 31797
    port: 80
    targetPort: 3000
    name: http
  selector:
    app: voidchan
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voidchan
  namespace: voidchan-ns
  labels:
    app: voidchan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voidchan
  template:
    metadata:
      labels:
        app: voidchan
    spec:
      containers:
      - name: voidchan
        imagePullPolicy: Always
        image: "voidchan/voidchan:latest"
        envFrom:
          - configMapRef:
              name: voidchan-api-cfg
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
        ports:
        - containerPort: 3000