apiVersion: v1
kind: Service
metadata:
  name: voidchan-api-service
  namespace: voidchan-ns
  labels:
    app: voidchan
spec:
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 31797
    port: 80
    targetPort: 3000
    name: http
  selector:
    app: voidchan
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voidchan
  namespace: voidchan-ns
  labels:
    app: voidchan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voidchan
  template:
    metadata:
      labels:
        app: voidchan
    spec:
      containers:
      - name: voidchan
        imagePullPolicy: Always
        image: "docker.pkg.github.com/voidchan/voidchan/voidchan:latest"
        envFrom:
          - configMapRef:
              name: voidchan-api-cfg
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
        ports:
        - containerPort: 3000