apiVersion: apps/v1
kind: Deployment
metadata:
  name: voidchan
  namespace: voidchan
  labels:
    app: voidchan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voidchan
  template:
    metadata:
      labels:
        app: voidchan
    spec:
      containers:
      - name: voidchan
        imagePullPolicy: Always
        image: "voidchan/voidchan:latest"
        envFrom:
          - configMapRef:
              name: voidchan-api-cfg
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
        ports:
        - containerPort: 3000